#!/usr/bin/env python3
"""Generate a consistent deployment identity set + sample election config.

The docker-compose deployments (RUNNING.md) need a *coherent* set of secp256k1
identities: each keyper's ``KEYPER_SIGNING_KEY`` must match the ``signing_key`` in
the election config, and the coordinator's key must match the ``COORDINATOR_IDENTITY``
the keypers pin. Hand-authoring that is error-prone, so this generates it all:

    python scripts/gen_deploy_env.py

Writes (under ``deploy/``, relative to repo root):
  * ``.env``               — all private keys + derived addresses for compose
  * ``sample-election.json`` — a valid §7.2 config envelope wiring the keyper
                               endpoints/addresses, admin/aggregator/gateway
                               identities, and a fresh eligibility key

The eligibility *private* key is printed (not stored in the config) — whoever runs
the eligibility service / issues voter attestations needs it. Voting window is set
relative to "now" so the sample is immediately registrable.
"""

from __future__ import annotations

import json
import os
import secrets
import sys
import time
from pathlib import Path

from eth_account import Account

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from geg.core.config import DuplicatePolicy, ElectionConfig, KeyperIdentity, Mode, Threshold, Variant  # noqa: E402
from geg.crypto import schnorr  # noqa: E402
from geg.crypto.points import g1_to_compressed  # noqa: E402
from geg.envelopes import codecs  # noqa: E402

N_KEYPERS = 3
T = 1  # (t, n) = (1, 3): any 2 of 3 decrypt


def _key():
    acct = Account.create()
    return acct.key.hex(), acct.address  # (0x-hex privkey, 0x checksummed address)


def main() -> None:
    admin_sk, admin_addr = _key()
    agg_sk, agg_addr = _key()
    gw_sk, gw_addr = _key()
    coord_sk, coord_addr = _key()
    relayer_sk, relayer_addr = _key()
    keypers = [_key() for _ in range(N_KEYPERS)]

    elig_sk, elig_vk = schnorr.keygen()
    elig_pub = g1_to_compressed(elig_vk)

    # Window offsets (seconds from now) — overridable for a short real-time demo:
    #   VOTING_START_OFFSET=60 VOTING_DURATION=90 TALLY_DURATION=1200
    now = int(time.time())
    start_off = int(os.environ.get("VOTING_START_OFFSET", "300"))   # leave time to run DKG
    duration = int(os.environ.get("VOTING_DURATION", "3300"))
    tally_dur = int(os.environ.get("TALLY_DURATION", "3600"))
    voting_start = now + start_off
    voting_end = voting_start + duration
    cfg = ElectionConfig(
        election_id=b"\x00" * 32,  # placeholder — the registry assigns the id at register
        num_candidates=3,
        budget=3,
        mode=Mode.EXACT,
        variant=Variant.A,
        weighted=True,
        max_weight=10,
        duplicate_policy=DuplicatePolicy.LAST_WINS,
        voting_start=voting_start,
        voting_end=voting_end,
        tally_deadline=voting_end + tally_dur,
        threshold=Threshold(t=T, n=N_KEYPERS),
        keypers=tuple(
            KeyperIdentity(signing_key=bytes.fromhex(addr[2:]), endpoint=f"http://keyper{i + 1}:8100")
            for i, (_sk, addr) in enumerate(keypers)
        ),
        eligibility_key=elig_pub,
        aggregator_key=bytes.fromhex(agg_addr[2:]),
        gateway_keys=(bytes.fromhex(gw_addr[2:]),),
        admin_key=bytes.fromhex(admin_addr[2:]),
        protocol_version="v1",
    )

    out = REPO / "deploy"
    out.mkdir(exist_ok=True)

    (out / "sample-election.json").write_text(json.dumps(codecs.enc_config(cfg), indent=2) + "\n")

    # Comments live on their own lines (never inline after a value) so the file
    # parses cleanly with `source`/`grep|cut`, not just docker compose --env-file.
    env_lines = [
        "# Generated by scripts/gen_deploy_env.py — one coherent identity set.",
        "# Private keys are secrets; this file is git-ignored. Do NOT commit.",
        "",
        f"ADMIN_SIGNING_KEY={admin_sk}",
        "# Bearer token for the admin HTTP service (:8300).",
        f"ADMIN_API_TOKEN={secrets.token_urlsafe(32)}",
        f"AGGREGATOR_SIGNING_KEY={agg_sk}",
        "# Aggregator address (20-byte) that keypers pin as a trusted bootstrapper.",
        f"AGGREGATOR_IDENTITY={agg_addr[2:].lower()}",
        f"GATEWAY_SIGNING_KEY={gw_sk}",
        f"COORDINATOR_SIGNING_KEY={coord_sk}",
        "# Coordinator address (20-byte) that keypers pin.",
        f"COORDINATOR_IDENTITY={coord_addr[2:].lower()}",
        "# Bearer token keypers present to the coordinator's write-relay endpoints.",
        f"COORDINATOR_API_TOKEN={secrets.token_urlsafe(32)}",
        "",
        "# Keyper identities (KEYPERn_KEY matches config keypers[n].signing_key).",
    ]
    for i, (sk, addr) in enumerate(keypers, start=1):
        env_lines.append(f"# keyper{i} address {addr}")
        env_lines.append(f"KEYPER{i}_KEY={sk}")
    env_lines += [
        "",
        "# Blockchain backend only: relayer that pays gas for keyper meta-tx writes.",
        f"# relayer address {relayer_addr}",
        f"GEG_RELAYER_KEY={relayer_sk}",
        "# GEG_CHAIN_RPC=http://anvil:8545",
        "# GEG_REGISTRY_ADDRESS=0x...   (set after deploying the registry — see RUNNING.md)",
        "",
        "# Eligibility service secret — issues voter attestations (its public key is",
        "# the config's eligibility_key). In production the eligibility service holds",
        "# this; here it lets scripts/vote_sample.py issue attestations for the demo.",
        f"ELIGIBILITY_PRIVATE_KEY={hex(elig_sk)}",
        "",
    ]
    (out / ".env").write_text("\n".join(env_lines))

    print(f"wrote {out/'.env'}")
    print(f"wrote {out/'sample-election.json'}")
    print(f"admin={admin_addr} aggregator={agg_addr} gateway={gw_addr}")
    print(f"coordinator={coord_addr} relayer={relayer_addr}")
    for i, (_sk, addr) in enumerate(keypers, start=1):
        print(f"keyper{i}={addr}")


if __name__ == "__main__":
    main()
